# Generated by Django 5.0.1 on 2024-03-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=300)),
                ('about_introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Home_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=300)),
                ('home_introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(upload_to='app_website/images/service_icons')),
                ('service_title', models.CharField(max_length=300)),
                ('service_description', models.TextField()),
            ],
        ),
    ]
