# Generated by Django 5.0.1 on 2024-03-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services_page',
            name='service_icon',
        ),
    ]
