# Generated by Django 5.0.1 on 2024-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0002_remove_services_page_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_page',
            name='event_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='events_page',
            name='event_name',
            field=models.CharField(default='edit', max_length=100),
        ),
        migrations.AddField(
            model_name='events_page',
            name='full_event_images',
            field=models.ImageField(default='1.jpg', upload_to='app_website/images/event_images'),
        ),
        migrations.AddField(
            model_name='events_page',
            name='thumbnail_image',
            field=models.ImageField(default='1.jpg', upload_to='app_website/images/event_thumbnails'),
        ),
    ]
