# Generated by Django 5.0.1 on 2024-03-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0005_alter_events_page_full_event_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiries_and_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=1000)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone_number', models.PositiveIntegerField()),
                ('sener_message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='events_page',
            name='full_event_images',
            field=models.ImageField(default=False, upload_to='images/event_images'),
        ),
        migrations.AlterField(
            model_name='events_page',
            name='thumbnail_image',
            field=models.ImageField(default=False, upload_to='images/event_thumbnails'),
        ),
    ]
