# Generated by Django 5.0.1 on 2024-03-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0006_inquiries_and_messages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_written', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
