# Generated by Django 5.0.1 on 2024-03-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0007_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_page',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='events_page',
            name='logistics',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='events_page',
            name='payment_details',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='events_page',
            name='prerequisites',
            field=models.TextField(default=False),
        ),
    ]
